#+TITLE: Dotfiles
#+AUTHOR: Anant Gupta


* What are dotfiles

Dotfiles are usully those files that usually begin with a period(.). The usually are hidden files. They are usually in Unix based system and they usually is used to customize our desktop. They are put because of my convience. Anyone is free to access my dotfiles.

* How you can use them
Actually I have put an install script named *install.sh*. It is also put for my convience. It is very easy to run. First make it executable by...

#+begin_src
chmod +x install.sh
#+end_src

Then run this by...

#+begin_src
./install.sh
#+end_src

NOTE: This will only work on Arch & Arch based system. If you want to need to work for Debian/Ubuntu distribution or any other you need to open the *install.sh* file & replace *yay* with your package manager helper. Also various packages are called differently on various other distribution (for instances alacritty). But this would work just fine on Arch based system.

* My various config
My various configs I use primarily use. Other config you can easily find on the dotfiles folder

- [[https://github.com/GuptaAnant/dotfiles/tree/master/.config/alacritty][Alacritty]]
- [[https://github.com/GuptaAnant/dotfiles/tree/master/.config/awesome][AwesomeWM]]
- [[https://github.com/GuptaAnant/dotfiles/tree/master/.doom.d][Doom Emacs]]
- [[https://github.com/GuptaAnant/dotfiles/tree/master/.config/fish][Fish]]
- [[https://github.com/GuptaAnant/dotfiles/tree/master/.config/picom][Picom]]
- [[https://github.com/GuptaAnant/dotfiles/tree/master/.config/rofi][Rofi]]
- [[https://github.com/GuptaAnant/dotfiles/blob/master/.config/starship.toml][Starship]]

* How To Manage Your Own Dotfiles
There are a hundred ways to manage your dotfiles. Personally, I use the *git bare repository method* for managing my dotfiles. Here is an article about this method of managing your dotfiles: [[https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/][From Developer Atlassian]]
