#+TITLE: Fish Shell Config
#+DESCRIPTION: My Fish shell config
#+AUTHOR: Anant Gupta
#+PROPERTY: header-args :tangle config.fish

* Table of content :toc:
- [[#about-this-config][About this config]]
- [[#adding-to-the-path][Adding to the path]]
- [[#exports][Exports]]
- [[#keybindings][Keybindings]]
- [[#path][Path]]
- [[#aliases][Aliases]]
- [[#starship-shell-prompt][Starship Shell Prompt]]

* About this config
Fish is a smart and user-friendly command line shell for Linux, macOS, and the rest of the family. This is my personal config of fish shell.

* Adding to the path
First line removes the path; second line sets it.  Without the first line,
your path gets massive and fish becomes very slow.

#+begin_src shell

set -e fish_user_paths
set -U fish_user_paths $HOME/.local/bin $HOME/Applications $fish_user_paths

#+end_src

* Exports
For automatic things
#+begin_src shell

set fish_greeting                                 # Supresses fish's intro message
set TERM "xterm-256color"                         # Sets the terminal type

#+end_src

* Keybindings
Vim or Emacs keybindings? It's your choice
#+begin_src shell

function fish_user_key_bindings
  # fish_default_key_bindings
  fish_vi_key_bindings
end

#+end_src

* Path
Exporting path for Doom Emacs
#+begin_src shell

export PATH="$HOME/.emacs.d/bin:$PATH"

#+end_src

* Aliases
Aliases usually refers to any other command. It usually shorten commands.
#+begin_src shell

# vim
alias vim='nvim'

# Changing "ls" to "exa"
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# the terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# For package
alias update="sudo pacman -Syyu"
alias install="yay -S"
alias remove="yay -Rs"

# Git bare repo setup
alias config="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"

# For wallpaper
alias cw="feh --bg-fill --randomize ~/wallpapers/"

#+end_src

* Starship Shell Prompt
A great shell prompt for bash, fish, zsh config

#+begin_src shell

starship init fish | source

#+end_src
